santosderek/Vitality

vitality/__init__.py

Added handlers for error pages 404, 403, 410, and 500.

Added error handlers for 404, 403, 410, and 500 pages

---

vitality/__init__.py

Incorporated Flask's logger into our functions

---

vitality/static/base.css
vitality/templates/index.html

Added a tests folder with a placeholder python file as a test. 
Added a static folder to place static files the webserver will need to fetch.
Added a url_for to give an example of how it works.
Added base.css as a template to use with url_for.

Santosderek dev

---

vitality/configuration.json
vitality/configuration.py

- Added a configuration JSON file to put credentials in a centralized manner. 
- Configuration.py is a wrapper class for the JSON file which returns credentials to specific services.
Mentioned in issue #15

First iteration of the configuration.py / configuration.json files

---

vitality/static/login.css
vitality/templates/createuser.html
vitality/templates/login.html

Wilson charles/dev

---

vitality/__init__.py
vitality/templates/createuser.html
vitality/templates/index.html
vitality/templates/login.html

- Added decorators to `__init__.py` to create routes for /login and /createuser. 
- Added links to login and createuser to index.html.  
- Fixed a bit of spelling. 
- Added url_for functions for some of the links.

Adding /login and /createuser

---

requirements.txt

We didn't need dnspython so I removed it.

Removed dnspython.

---

vitality/__init__.py
vitality/static/login.css
vitality/templates/createuser.html
vitality/templates/login.html
vitality/templates/profile.html
vitality/user.py

The application now allows user creation and user login. This is achieved using Flask's session and g modules. 
- There is a global (later needs to be changed to a database) user list that stores all the User classes that have been created. 
- So far /Createuser creates a new class to be appended to this list, and /login looks into this list and appends the user_id to the session while checking that the username and password combo match. 
- I also added a /profile page to return the username and user id to the screen to make sure everything was working. 
- User.py is a class that holds user data. 
Some formatting of login.html and createuser.html were necessary for this feature.

Added /login and /createuser functionality

---

vitality/__init__.py
vitality/templates/profile.html
vitality/templates/usersettings.html
vitality/user.py

Set up user settings page as well as functional decorator and small changes to profile.html and user.py

User settings page

---

requirements.txt
vitality/__init__.py

I added the Markupsafe module and escaped all user input. Let me know if this looks good. Only doing this for routes `/login` and `/createuser` Following #26. 
We will have to use this module on all user input from here on out. 
NOTE: Make sure to `pip3 install -r reqirements.txt` to install the new Markupsafe module.

Escaped user input using the Markupsafe package.

---

vitality/__init__.py

Added the escape function surounding the user input in user settings.
Check if it is acceptable for #37.

Added the escape function surounding the user input in user settings.

---

vitality/templates/workoutlist.html

It is located in the future function `def workoutlist()`.

Fixed bug where workout.html is not in the static folder. 

---

vitality/workout.py

Fixed name within as_dict

---

tests/test_database.py
vitality/database.py

Added more tests to test_database.py

Added more tests to test_database.py

---

configuration.json
tests/test_database.py
vitality/__init__.py
vitality/configuration.py

The Mongo_URI is now populated from the Configuration class, and can be changed in the configuration.json file.

Added the configuration class to the init and test files

---

tests/test_database.py
vitality/database.py
vitality/workout.py

Laruffaelijah dev

---

vitality/trainer.py

Not the most familiar with inheritance in Python yet, but I think I did this right? I wasn't sure about how the as_dict should work exactly. Can y'all take a look and let me know if this is right?

Created trainer.py

---

vitality/__init__.py
vitality/templates/profile.html
vitality/templates/usersettings.html

Added a logout button and route to log the user out

---

vitality/__init__.py

Fixing bug where when logging in, the profile page redirect would error out.

Login redirect bug fix

---

tests/test_trainer.py
tests/test_user.py

Tests the current as_dict() method and provides places for future methods added to trainer and user to be tested as well.

Added test_user.py and test_trainer.py

---

vitality/static/css/base.css
vitality/templates/account/login.html
vitality/templates/account/signup.html

- Formatted the login and signup pages. 
- Added the primary colors we will be using throughout the website. 
- Fixed wording and removed unnecessary labels.

Formatted and laid out the foundation of the login and sign up pages.

---

vitality/__init__.py
vitality/templates/account/profile.html
vitality/templates/trainee/list_trainers.html
vitality/templates/trainee/overview.html
vitality/templates/trainee/schedule.html

Closes #83 
- Added list_trainers.html and schedule.html to the trainee directory.
- Linked all pages together. Fixed some formatting and consistancy styling.

Created trainee pages. 

---

vitality/templates/base.html

Closes #101 
- Added a loading spinner while page loads. 
- Content is hidden until onload and then the spinner and content switches visible state.

Added a loading spinner while page loads.

---

requirements.txt
tests/test_flask.py
vitality/__init__.py
vitality/templates/error/400.html

- Added all tests for all functions in our flask application. 
- We will need to update the skipped trainer pagers in the future.

Added tests for flask app

---

tests/test_database.py
tests/test_flask.py
tests/test_user.py
vitality/__init__.py
vitality/database.py
vitality/trainee.py
vitality/trainer.py
vitality/user.py

Closes #64 
- Added Trainer functions to database and test functions. 
- I also refactored User class into Trainee class
- Now both Trainee and Trainer classes inherit the User class.

Added Trainer Functions and added Trainee class

---

vitality/database.py

Added a ***_dict_to_class to Trainee, Trainer, and Workout functions since a portion of code could be optimized.

Optimizations with database class

---

helper/schema_atlas.py
helper/schema_local.py
tests/test_database.py
tests/test_flask.py
vitality/__init__.py
vitality/database.py
vitality/user.py
vitality/workout.py

- Database unit test now has setup and teardown functions to create the test Trainee, Trainer, and Workout classes. 
- Changed all `== None` to `is None`. (Proper way) 
- Added workout test functions. 
- Used `deepcopy` to create a copy of the test classes.

Improved unit tests.

---

tests/test_flask.py
vitality/__init__.py
vitality/templates/account/signup.html
vitality/templates/trainer/list_trainees.html

- Added functionality to sign up and login as a Trainer and Trainee. 
Closes #82

User can now sign up and login as both a Trainee or Trainer.

---

.gitignore

- g.user_type helps with context of the type of user they are
- Added coverage files to .gitignore

Fixed navbar

---

vitality/__init__.py
vitality/database.py
vitality/templates/base.html

- Added functions to get trainer/trainee ids by login info. 
- Fixed navbar bug where trainee would go to trainer pages and vice versa.

Refactored code that was reused multiple times. 

---

tests/test_flask.py
vitality/__init__.py
vitality/database.py

- Better setup and teardown for test_flask. database.py has better formatting.
- Added more checks to see if trainers and trainees get 403 if on the wrong page.

test_flask more checks

---

tests/test_flask.py

- Added more checks to test_flask 
- Added login_as_testTrainer and login_as_testTrainee for less code complexity

Adding more checks to test_flask

---

tests/test_database.py
tests/test_flask.py
tests/test_trainer.py
tests/test_user.py
vitality/__init__.py
vitality/configuration.py
vitality/database.py
vitality/templates/account/profile.html
vitality/templates/account/signup.html
vitality/templates/account/usersettings.html
vitality/templates/trainee/add_trainer.html
vitality/templates/trainee/overview.html
vitality/trainee.py
vitality/trainer.py
vitality/user.py
vitality/workout.py

- Added more tests to increase code coverage
- Added hints to all parameters
- Replaced `add_trainee_by_id` and `add_trainee_by_username` with `add_trainee_class_by_id` and `add_trainee_class_by_username` for code simplicity. 
- Merged `firstname` and `lastname` to `name`.

Tests, hints, code simplicity

---

tests/test_flask.py
vitality/__init__.py
vitality/static/css/base.css
vitality/static/css/sidebar.css
vitality/templates/trainee/add_trainer.html
vitality/templates/trainee/list_trainers.html
vitality/templates/trainee/overview.html
vitality/templates/trainee/schedule.html
vitality/templates/trainer/list_trainees.html
vitality/templates/trainer/overview.html
vitality/templates/trainer/schedule.html

Closes #86 
- Able to search for trainers by name. 
- Split sidebar css to separate file.

Added Trainer search 

---

tests/test_database.py
tests/test_flask.py
tests/test_trainer.py
vitality/trainee.py
vitality/trainer.py
vitality/user.py

User class now updates self.__dict__ as is now subscriptable.

User class constructors now use __dict__ 

---

tests/test_database.py
tests/test_flask.py
tests/test_trainer.py
tests/test_user.py
vitality/__init__.py
vitality/database.py
vitality/trainee.py
vitality/trainer.py
vitality/user.py
vitality/workout.py

- Changed all .id to ._id. 
- Added trainers list to Trainee class.

Replaced all .id to ._id and trainers list to Trainee

---

vitality/__init__.py

Fixed profile page. Now checks the trainer db to see if there are any users with a matching username.

Fixing profile page. Now checking trainers.

---

tests/test_trainee.py
tests/test_trainer.py
vitality/user.py

Closes #81 
- Updated User class to reflect the UML. 
- Updated respective tests to reflect UML.

Updated the user class according to the UML.

---

vitality/trainee.py
vitality/trainer.py
vitality/user.py

__dict__ updates with all class values so theres no need to do a __dict__.update.

Removed the __dict__.update commands from user class. 

---

tests/test_database.py
tests/test_trainer.py
vitality/__init__.py
vitality/database.py
vitality/user.py

- Removed all prints. 
- Fixed raise calls to InvalidCharactersException; should have been one if statement for cleaner code. 
- Within the user class, needed to copy the dict since add_trainer/trainee functions would use this `__dict__` and change values.
- Trainer will now insert using the `__dict__` parameter which allows add_trainer to be dependent on the class definition instead of having to update this function every time a new property is added.

Making add_trainee/trainer insert the class dictionary so it is dependent on the class definition. 

---

tests/test_database.py
tests/test_flask.py
vitality/__init__.py
vitality/database.py
vitality/templates/trainee/list_trainers.html
vitality/templates/trainee/overview.html
vitality/templates/trainee/trainer_search.html
vitality/trainee.py
vitality/trainer.py

- Mongodb documents are now entirely dependent on our created Trainee, Trainer, User, and Workout classes. 
- Trainees can now add trainers by searching for their name. 
- Renamed add_trainer to trainer_search and added new functionality to /add_trainer route. 
- Overview should now reflect all added trainers in trainee overview. 
- Further optimizations.
Closes #85

Trainee can now add trainer. 

---

tests/test_database.py
tests/test_flask.py
vitality/__init__.py
vitality/database.py
vitality/templates/trainer/overview.html
vitality/templates/trainer/trainee_search.html

- Added the ability for a trainer to add a trainee. 
- Added ability for trainer to list trainees; If trainee is found, button will be greyed out.
- Added appropriate unit tests.
Closes #153

Trainers can now add trainees by search

---

vitality/__init__.py
vitality/templates/account/delete.html
vitality/templates/account/usersettings.html
vitality/templates/navbar.html

Added user settings to navbar as well as pages and functionality for deleting user profiles. I wasn't sure if I needed to add any unit tests for it.

user settings features

---

tests/test_flask.py
vitality/__init__.py
vitality/templates/sidebar.html
vitality/templates/user/overview.html

- Fixed bug where wrong links were given to the opposite class.
- Shortened /trainee_list_trainers and /trainer_list_trainees to /list_trainers and /list_trainees.

Fixed bug where wrong links were given to the opposite class

---

tests/test_flask.py
vitality/__init__.py

Added input validation for /usersettings and three new unit tests.

---

tests/test_flask.py
vitality/__init__.py
vitality/templates/account/login.html
vitality/templates/account/signup.html
vitality/templates/account/usersettings.html

166 Added try/exception, updated unit tests, added alert to webpages for invalid inputs.

---

Dockerfile

Adding Dockerfile to use with docker-compose and automate deployments of the flask application.
This is the Docker file that I am using with my VPC to containerize our app. If you want to use docker with our app you could with this file.

Added dockerfile to use with docker-compose

---

README.md

Update README.md with Launch Instructions

---

README.md

- Gave a warning to use sudo if they need root privileges. 
- Fixed numbering

Numbering and sudo

---

.github/workflows/Unittests-and-Dependencies.yml

Adding a test within the github action workflow to check if Docker build works.

Docker build GH action

---

tests/test_database.py
tests/test_flask.py
vitality/__init__.py

Usernames are now lowercase and uppercase tests added

---

vitality/__init__.py
vitality/templates/account/login.html
vitality/templates/account/signup.html
vitality/templates/account/usersettings.html

- Added JavaScript to force user to use lowercase with usernames.
- Also added more fitting message within the exceptions.

Added JavaScript to force user to use lowercase with usernames.

---

tests/test_trainee.py
tests/test_trainer.py
tests/test_user.py
tests/test_workout.py
vitality/trainer.py
vitality/workout.py

Added more tests and repr functions.

---

vitality/templates/trainee/trainer_search.html
vitality/templates/trainer/trainee_search.html

- Fixed bug where the wrong button would get greyed out when adding a trainee.
- Fixed bug where the wrong button would get greyed out when adding a trainer.
Please check that the correct button gets greyed out when selecting from a list of trainees / trainers to invite as a friend.

Fixed bug where the wrong button gets greyed out when inviting a user as a friend. 

---

.github/workflows/Unittests-and-Dependencies.yml
ansible/UpdateVitality.yml

Adding a step to automatically deploy vitality to the cloud through ansible.

Continuous Deployment

---

helper/default_workouts.py
tests/test_database.py
tests/test_flask.py
tests/test_trainee.py
tests/test_trainer.py
tests/test_user.py
tests/test_workout.py
vitality/__init__.py
vitality/database.py
vitality/static/css/base.css
vitality/templates/account/profile.html
vitality/templates/user/list_added.html
vitality/templates/workout/new_workout.html
vitality/templates/workout/search.html
vitality/templates/workout/workout.html
vitality/user.py
vitality/workout.py

- Merged both profile routes into one. Additional formatting.
- Merged all get_workout_'attribute' functions into one function that takes kwargs. This then gets passed to the find_one mongo function as an easier implementation.
- Removing exp from workout class since its redundant. EXP can be calculated from default values within workout file.
- Adding a section before app creation to populate a default trainer and workouts.
- Added the ability to dynamically populate the default search workouts based on the Workouts provided by the vitality default user.
- Added all user attributes to profile page.
- Added ability for submit button to be greyed out upon completion. Form now does a POST to update the workout.
- Form now does a POST to workout function.
- Updated the workout function to …

Recommended changes for /workout

---

helper/default_workouts.py
tests/test_database.py
tests/test_flask.py
tests/test_trainee.py
tests/test_trainer.py
tests/test_user.py
tests/test_workout.py
vitality/__init__.py
vitality/database.py
vitality/static/css/base.css
vitality/templates/account/profile.html
vitality/templates/user/list_added.html
vitality/templates/workout/new_workout.html
vitality/templates/workout/search.html
vitality/templates/workout/workout.html
vitality/user.py
vitality/workout.py

Created schema of default workouts which are now shown above the search bar on the workout search, predefined workouts also have experience points shown based on difficulty. Lastly, added functionality for workout exp to be given to the user upon completion. Workouts now have a property called is_completed. If the user presses on "complete", the workout is marked as complete and the exp is calculated accordingly. NOTE: Possible issues with multiple workouts of the same exp that are added. Suggestions are welcome.
Closes #192

Gain experience points by workout

---

vitality/database.py
vitality/user.py

Added if statement, and defaults for lng and lat are now 0.

Fixes for location

---

vitality/templates/workout/workout.html

Removed unused parameters, on fail, button turns red for 2 seconds.

Fixed issues found from meeting

---

tests/test_flask.py
vitality/__init__.py
vitality/templates/features.html
vitality/templates/home.html
vitality/templates/navbar.html

Closes #32 
- Created the features page and mimicked the Marvel prototype.
- Added Unit test

Features Page

---

vitality/templates/workout/workout.html

If times are not provided, tell user.

Not provided

---

requirements.txt
tests/test_flask.py
tests/test_youtube.py
vitality/templates/user/map.html
vitality/youtube.py

Re-added an img tag that is needed by google maps.

Re-added place-icon img tag.
